version: '3.8'

services:
    blitz-dev:
        container_name: blitzjs_frontend_dev
        image: blitzjs-frontend-dev:1.0.0
        build:
          context: ./blitzjs-frontend/
          dockerfile: ./Dockerfile
        command: blitz start
        ports: 
            - 3004:3000
        networks:
            - nesjs-network
        volumes:
            - ./blitzjs-frontend/:/app
            - /app/node_modules
        restart: unless-stopped
        depends_on: 
            - dev
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: ./nestjs-backend/
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3005:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - ./nestjs-backend:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: ./nestjs-backend/
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3005:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - ./nestjs-backend:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: